services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  Banovo\SSOSysuserBundle\Sysuser:
    class: Banovo\SSOSysuserBundle\Sysuser
    arguments:
      - "@=parameter('banovo_sso_sysuser')"
